/// Write a .team.yaml file from team state.
/// Output goes to ~/.masques/ (private, outside repo).

const std = @import("std");
const state_mod = @import("state.zig");

pub fn writeTeamYaml(app: *const state_mod.AppState) ![]const u8 {
    const team_name = app.teamName();

    // Sanitize filename
    var filename_buf: [256]u8 = undefined;
    var fi: usize = 0;
    for (team_name) |c| {
        if (fi >= 250) break;
        if (c == ' ') {
            filename_buf[fi] = '-';
        } else {
            filename_buf[fi] = std.ascii.toLower(c);
        }
        fi += 1;
    }
    const basename = filename_buf[0..fi];

    // Resolve output directory: $MASQUES_HOME or ~/.masques
    const home = std.posix.getenv("MASQUES_HOME") orelse blk: {
        const h = std.posix.getenv("HOME") orelse return error.NoHomeDir;
        break :blk h;
    };

    var dir_buf: [512]u8 = undefined;
    const dir_path = if (std.posix.getenv("MASQUES_HOME")) |_|
        try std.fmt.bufPrint(&dir_buf, "{s}", .{home})
    else
        try std.fmt.bufPrint(&dir_buf, "{s}/.masques", .{home});

    // Ensure directory exists
    std.fs.cwd().makePath(dir_path) catch {};

    var path_buf: [768]u8 = undefined;
    const path = try std.fmt.bufPrint(&path_buf, "{s}/{s}.team.yaml", .{ dir_path, basename });

    var buf: [4096]u8 = undefined;
    var fbs = std.io.fixedBufferStream(&buf);
    const w = fbs.writer();

    try w.writeAll("# Generated by Masques TUI\n");
    try std.fmt.format(w, "name: {s}\n", .{team_name});

    // Emit intent as a YAML block scalar
    const intent = app.teamIntent();
    if (intent.len > 0) {
        try w.writeAll("intent: |\n");
        // Prefix each line with 2 spaces
        var start: usize = 0;
        while (start < intent.len) {
            const end = std.mem.indexOfScalarPos(u8, intent, start, '\n') orelse intent.len;
            try w.writeAll("  ");
            try w.writeAll(intent[start..end]);
            try w.writeAll("\n");
            start = if (end < intent.len) end + 1 else intent.len;
        }
    }

    try w.writeAll("\nroster:\n");

    for (app.team[0..app.team_count]) |slot| {
        if (slot) |member| {
            try std.fmt.format(w, "  - masque: {s}\n", .{member.name});
            if (member.version.len > 0) {
                try std.fmt.format(w, "    version: \"{s}\"\n", .{member.version});
            }
        }
    }

    const content = fbs.getWritten();

    const file = try std.fs.cwd().createFile(path, .{});
    defer file.close();
    try file.writeAll(content);

    return path;
}

pub fn writeMasqueYaml(app: *const state_mod.AppState) !void {
    const name = app.masque_name_buf[0..app.masque_name_len];
    const domain = app.masque_domain_buf[0..app.masque_domain_len];
    const who = app.masque_who_buf[0..app.masque_who_len];
    const what = app.masque_what_buf[0..app.masque_what_len];
    const how = app.masque_how_buf[0..app.masque_how_len];
    const why = app.masque_why_buf[0..app.masque_why_len];

    // Sanitize filename
    var filename_buf: [256]u8 = undefined;
    var fi: usize = 0;
    for (name) |c| {
        if (fi >= 250) break;
        if (c == ' ') {
            filename_buf[fi] = '-';
        } else {
            filename_buf[fi] = std.ascii.toLower(c);
        }
        fi += 1;
    }
    const basename = filename_buf[0..fi];

    // Resolve output directory
    const home = std.posix.getenv("MASQUES_HOME") orelse blk: {
        const h = std.posix.getenv("HOME") orelse return error.NoHomeDir;
        break :blk h;
    };

    var dir_buf: [512]u8 = undefined;
    const dir_path = if (std.posix.getenv("MASQUES_HOME")) |_|
        try std.fmt.bufPrint(&dir_buf, "{s}", .{home})
    else
        try std.fmt.bufPrint(&dir_buf, "{s}/.masques", .{home});

    std.fs.cwd().makePath(dir_path) catch {};

    var path_buf: [768]u8 = undefined;
    const path = try std.fmt.bufPrint(&path_buf, "{s}/{s}.masque.yaml", .{ dir_path, basename });

    var buf: [4096]u8 = undefined;
    var fbs = std.io.fixedBufferStream(&buf);
    const w = fbs.writer();

    try w.writeAll("# Generated by Masques TUI\n");
    try std.fmt.format(w, "name: {s}\n", .{name});
    try w.writeAll("version: \"0.1.0\"\n");

    if (domain.len > 0 or why.len > 0) {
        try w.writeAll("\nattributes:\n");
        if (domain.len > 0) try std.fmt.format(w, "  domain: {s}\n", .{domain});
        if (why.len > 0) try std.fmt.format(w, "  tagline: \"{s}\"\n", .{why});
    }

    if (who.len > 0) {
        try w.writeAll("\ncontext: |\n");
        try std.fmt.format(w, "  {s}\n", .{who});
    }

    try w.writeAll("\nlens: |\n");
    try std.fmt.format(w, "  You are {s}.\n", .{name});
    if (what.len > 0) {
        try w.writeAll("\n");
        try std.fmt.format(w, "  What you do: {s}\n", .{what});
    }
    if (how.len > 0) {
        try w.writeAll("\n");
        try std.fmt.format(w, "  How you work: {s}\n", .{how});
    }
    if (why.len > 0) {
        try w.writeAll("\n");
        try std.fmt.format(w, "  Why this matters: {s}\n", .{why});
    }

    const content = fbs.getWritten();

    const file = try std.fs.cwd().createFile(path, .{});
    defer file.close();
    try file.writeAll(content);
}
